### PR TITLE
SCMOD-3059: Updated to correct issues with element tags from lotus no…

### PR DESCRIPTION
**Pull request by Anthony-McGreevy**
https://jira.autonomy.com/browse/SCMOD-3059

…tes emls

### CODE REVIEW

**Comment by Anthony-McGreevy** [comment]
**TEST BUILD:** http://sou-jenkins2.hpeswlab.net/job/caf/view/Developer/job/caf~worker-familyhashing~SCMOD-3059~CI/1/console

**Review by dermot-hardy — CHANGES_REQUESTED** [review]
As discussed, the actual issue is in the block above.

**Comment by Anthony-McGreevy** [comment]
@dermot-hardy Can you take a look at this PR again please. I have made some changes to reflect your comments.

**Review by dermot-hardy — CHANGES_REQUESTED** [review]
It's too complex - it shouldn't reset the loop when building the new string.

**Comment by Anthony-McGreevy** [comment]
@dermot-hardy I have simplified the code and rerun the test build and the new IT for lotus notes is still passing.

**Review by dermot-hardy — COMMENTED** [review]
Great.  As discussed, just comment the `sanitizeElementName` function.

**Comment by Anthony-McGreevy** [comment]
@dermot-hardy Updated to add method comments and changed return statement to use null instead of returning the startChar for clarity

**Review by dermot-hardy — APPROVED** [review]

**Pull request merged**
